export const fake_data = [
  {pic:'fake_data/pictures/profilpic.png', name:'Wade Wilson', date: '7 février 1999', text: `Le film commence fort, avec une belle baston reprenant les bruits typiques d’un Bud Spencer et Terence Hill, avec l’air de musique de la Cantina de Star Wars, hilarité totale pour ma part ! 
  Par la suite, j’ai finalement trouvé la musique assez bonne, variée, rythmée et originale. Les chants et chorégraphie sympa (même si j’en ai passés certains vers la fin en accélérée). 
  Les cascades improbables`, edit: true  },
  {pic:'fake_data/pictures/profilpic.png', name:'Wade Wilson', date: '7 février 1999', text: `Le film commence fort, avec une belle baston reprenant les bruits typiques d’un Bud Spencer et Terence Hill, avec l’air de musique de la Cantina de Star Wars, hilarité totale pour ma part ! 
  Par la suite, j’ai finalement trouvé la musique assez bonne, variée, rythmée et originale. Les chants et chorégraphie sympa (même si j’en ai passés certains vers la fin en accélérée). 
  Les cascades improbables m’ont...
  Le film commence fort, avec une belle baston reprenant les bruits typiques d’un Bud Spencer et Terence Hill, avec l’air de musique de la Cantina de Star Wars, hilarité totale pour ma part ! 
  Par la suite, j’ai finalement trouvé la musique assez bonne, variée, rythmée et originale. Les chants et chorégraphie sympa (même si j’en ai passés certains vers la fin en accélérée). 
  Les cascades improbables m’ont bien fait marrer, ainsi que le méchant, avec sa tête de vainqueur qui ne peut juste pas faire peur. Les courses poursuites en voitures ont un rendu des plus étranges… et le tout me semble presque d’être un film expérimental. Des fois, ça donne des bonnes surprises, et des fois, c’est totalement raté. J’ai particulièrement apprécié les plans sur la vie courante indienne, avant de revenir par un dézoom à une scène de course poursuite. 
  Maintenant les gros hics : finalement le film ne parle pas vraiment de Kabaddi, et cela, ça me rend triste. C’est juste un prétexte pour donner le l’attrait au film. Autre chose, le scénario est vraiment old school et patriarcal au possible : un homme qui défie un gros méchant pour sauver une fille sans défense cucul la praline. C’est pourri. Bon, maintenant on est en Inde, ça reste pourri, mais je suis un peu plus tolérant que si ça avait été une production occidentale. Et 3h00 pour un tel scénario post-it, ce n’est juste pas possible ! On aurait très facilement pu retirer 1h30. En tout cas, pour l’instant, le meilleur film que j’ai vu de la S3 de cinévorace.`},
  {pic:'fake_data/pictures/profilpic.png', name:'Wade Wilson', date: '7 février 1999', text: `Le film commence fort, avec une belle baston reprenant les bruits typiques d’un Bud Spencer et Terence Hill, avec l’air de musique de la Cantina de Star Wars, hilarité totale pour ma part ! 
  Par la suite, j’ai finalement trouvé la musique assez bonne, variée, rythmée et originale. Les chants et chorégraphie sympa (même si j’en ai passés certains vers la fin en accélérée). 
  Les cascades improbables m’ont...
  Le film commence fort, avec une belle baston reprenant les bruits typiques d’un Bud Spencer et Terence Hill, avec l’air de musique de la Cantina de Star Wars, hilarité totale pour ma part ! 
  Par la suite, j’ai finalement trouvé la musique assez bonne, variée, rythmée et originale. Les chants et chorégraphie sympa (même si j’en ai passés certains vers la fin en accélérée). 
  Les cascades improbables m’ont bien fait marrer, ainsi que le méchant, avec sa tête de vainqueur qui ne peut juste pas faire peur. Les courses poursuites en voitures ont un rendu des plus étranges… et le tout me semble presque d’être un film expérimental. Des fois, ça donne des bonnes surprises, et des fois, c’est totalement raté. J’ai particulièrement apprécié les plans sur la vie courante indienne, avant de revenir par un dézoom à une scène de course poursuite. 
  Maintenant les gros hics : finalement le film ne parle pas vraiment de Kabaddi, et cela, ça me rend triste. C’est juste un prétexte pour donner le l’attrait au film. Autre chose, le scénario est vraiment old school et patriarcal au possible : un homme qui défie un gros méchant pour sauver une fille sans défense cucul la praline. C’est pourri. Bon, maintenant on est en Inde, ça reste pourri, mais je suis un peu plus tolérant que si ça avait été une production occidentale. Et 3h00 pour un tel scénario post-it, ce n’est juste pas possible ! On aurait très facilement pu retirer 1h30. En tout cas, pour l’instant, le meilleur film que j’ai vu de la S3 de cinévorace.`},
  {pic:'fake_data/pictures/profilpic.png', name:'Wade Wilson', date: '7 février 1999', text: `Le film commence fort, avec une belle baston reprenant les bruits typiques d’un Bud Spencer et Terence Hill, avec l’air de musique de la Cantina de Star Wars, hilarité totale pour ma part ! 
  Par la suite, j’ai finalement trouvé la musique assez bonne, variée, rythmée et originale. Les chants et chorégraphie sympa (même si j’en ai passés certains vers la fin en accélérée). 
  Les cascades improbables m’ont...
  Le film commence fort, avec une belle baston reprenant les bruits typiques d’un Bud Spencer et Terence Hill, avec l’air de musique de la Cantina de Star Wars, hilarité totale pour ma part ! 
  Par la suite, j’ai finalement trouvé la musique assez bonne, variée, rythmée et originale. Les chants et chorégraphie sympa (même si j’en ai passés certains vers la fin en accélérée). 
  Les cascades improbables m’ont bien fait marrer, ainsi que le méchant, avec sa tête de vainqueur qui ne peut juste pas faire peur. Les courses poursuites en voitures ont un rendu des plus étranges… et le tout me semble presque d’être un film expérimental. Des fois, ça donne des bonnes surprises, et des fois, c’est totalement raté. J’ai particulièrement apprécié les plans sur la vie courante indienne, avant de revenir par un dézoom à une scène de course poursuite. 
  Maintenant les gros hics : finalement le film ne parle pas vraiment de Kabaddi, et cela, ça me rend triste. C’est juste un prétexte pour donner le l’attrait au film. Autre chose, le scénario est vraiment old school et patriarcal au possible : un homme qui défie un gros méchant pour sauver une fille sans défense cucul la praline. C’est pourri. Bon, maintenant on est en Inde, ça reste pourri, mais je suis un peu plus tolérant que si ça avait été une production occidentale. Et 3h00 pour un tel scénario post-it, ce n’est juste pas possible ! On aurait très facilement pu retirer 1h30. En tout cas, pour l’instant, le meilleur film que j’ai vu de la S3 de cinévorace.`},
  
];

export default fake_data;